#!/bin/bash
# ARIA Token Management Dashboard

SCRIPTS_DIR="/Users/apple/.gemini/_scripts"

echo "==========================================="
echo "ARIA TOKEN MANAGEMENT SYSTEM"
echo "==========================================="
echo ""
echo "1. MEMORY HEALTH"
/Users/apple/.gemini/_scripts/memory_health.sh
echo ""
echo "2. DESKTOP COMMANDER"
echo "   Status: $(npx @wonderwhy-er/desktop-commander@latest status 2>&1 | head -1)"
echo "   Config: /Users/apple/.claude-server-commander/config.json"
echo ""
echo "3. CONTEXT WINDOW"
echo "   Manager: ACTIVE"
echo "   Strategy: tiered (small/medium/large)"
echo "   Auto-trim: 20 turn limit, preserve 5"
echo ""
echo "==========================================="
echo "SETUP COMPLETE"
echo "==========================================="
echo ""
echo "Token reduction mechanisms active:"
echo "  ✓ Memory tier compression (50/30 line limits)"
echo "  ✓ Health monitoring with auto-alerts"
echo "  ✓ Context window strategies"
echo "  ✓ DesktopCommanderMCP file operations"
echo "  ✓ Serial position optimization"
echo "  ✓ Importance-based summarization"
echo ""
echo "Commands:"
echo "  ~/.gemini/_scripts/memory_health.sh"
echo "  ~/.gemini/_scripts/compression_engine.sh"
echo "  ~/.gemini/_scripts/context_window_manager.sh"
echo ""
echo "Documentation: ~/.gemini/ARIA_TOKEN_MGMT.md"
